version: "2.1"

services:
  checkout:
    container_name: checkout
    build:
      dockerfile: Dockerfile
      context: checkout
    ports:
      - "3000:3000"
    depends_on:
      - broker
      - zoo
    environment:
      KAFKA_BROKER: "broker:9092"

  inventory:
    container_name: inventory
    build:
      dockerfile: Dockerfile
      context: inventory
    depends_on:
      - broker
      - zoo
    environment:
      KAFKA_BROKER: "broker:9092"

  zoo:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo:2888:3888

  broker:
    image: confluentinc/cp-kafka:7.3.2
    hostname: broker
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zoo

  init-kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - broker
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
        kafka-topics --bootstrap-server broker:9092 --list
        kafka-topics --bootstrap-server broker:9092 --create --if-not-exists --topic checkout --replication-factor 1 --partitions 1
        kafka-topics --bootstrap-server broker:9092 --list
      "

  # inventory:
  #   container_name: inventory
  #   build:
  #     dockerfile: Dockerfile
  #     context: inventory
  #   ports:
  #     - "3001:3001"

  # shipment:
  #   container_name: shipment
  #   build:
  #     dockerfile: Dockerfile
  #     context: shipment
  #   ports:
  #     - "3002:3002"

  # order:
  #   container_name: order
  #   build:
  #     dockerfile: Dockerfile
  #     context: order
  #   ports:
  #     - "3003:3003"
