version: "2.1"

services:

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  checkout:
    container_name: checkout
    build:
      dockerfile: Dockerfile
      context: checkout
    depends_on:
      - broker
      - zoo
      - traefik
    labels:
      - "traefik.http.routers.checkout.rule=Host(`localhost`) && PathPrefix(`/api/checkout`)"
      - "traefik.http.middlewares.checkout-stripprefix.stripprefix.prefixes=/api/checkout"
      - "traefik.http.routers.checkout.middlewares=checkout-stripprefix"
    environment:
      KAFKA_BROKER: "broker:9092"

  inventory:
    container_name: inventory
    build:
      dockerfile: Dockerfile
      context: inventory
    depends_on:
     - traefik
    environment:
      KAFKA_BROKER: "broker:9092"

  merchant:
    container_name: merchant
    build:
      dockerfile: Dockerfile
      context: merchant
    depends_on:
     - traefik
    labels:
      - "traefik.http.routers.merchant.rule=Host(`localhost`) && PathPrefix(`/api/merchant`)"
      - "traefik.http.middlewares.merchant-stripprefix.stripprefix.prefixes=/api/merchant"
      - "traefik.http.routers.merchant.middlewares=merchant-stripprefix"

  shipment:
    container_name: shipment
    build:
      dockerfile: Dockerfile
      context: shipment
    depends_on:
     - traefik
    environment:
      KAFKA_BROKER: "broker:9092"

  notification:
    container_name: notification
    build:
      dockerfile: Dockerfile
      context: notification
    depends_on:
     - traefik
    environment:
      KAFKA_BROKER: "broker:9092"

  zoo:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo:2888:3888

  broker:
    image: confluentinc/cp-kafka:7.3.2
    hostname: broker
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zoo
